# Generated by Django 4.2.1 on 2023-07-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.item')),
                ('damage_type', models.CharField(choices=[('Physical', 'Physical'), ('Fire', 'Fire'), ('Water', 'Water'), ('Wind', 'Wind'), ('Light', 'Light'), ('Dark', 'Dark')], max_length=10)),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('dexterity', models.IntegerField()),
            ],
            bases=('users.item',),
        ),
        migrations.AddField(
            model_name='character',
            name='active_slots',
            field=models.JSONField(default=dict),
        ),
    ]
